unit TestFolderPathsForm;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, GUITesting, StdCtrls, Buttons, Classes, SysUtils, Windows, Dialogs, Forms,
  FolderPathsForm, Controls, Graphics, Messages;
type
  // Test methods for class TfrmFolderPaths

  TestTfrmFolderPaths = class(TGUITestCase)
  private
    FfrmFolderPaths: TfrmFolderPaths;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  Published
    Procedure TestTabOrder;
  end;

implementation

procedure TestTfrmFolderPaths.SetUp;
begin
  FfrmFolderPaths := TfrmFolderPaths.Create(Application.MainForm);
end;

procedure TestTfrmFolderPaths.TearDown;
begin
  FfrmFolderPaths.Free;
  FfrmFolderPaths := nil;
end;

procedure TestTfrmFolderPaths.TestTabOrder;

begin
  //Chec
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTfrmFolderPaths.Suite);
end.


